import { StandardMerkleTree } from "@openzeppelin/merkle-tree";
import { fixturePath, writeJson, writeText } from "./io.js";
import { LEAF_ENCODING, type LeafValue } from "./leaves.js";

/**
 * DETERMINISTIC fixture builder — NO RPC. Builds a StandardMerkleTree over a fixed synthetic value
 * set with the EXACT on-chain leaf encoding (["address","uint256","uint256"]), then emits a JSON
 * fixture and a paste-ready Solidity snippet for the contract test suite.
 *
 * Internally asserts StandardMerkleTree.verify passes for every entry against the root, so a failed
 * encoding/library mismatch breaks the build loudly.
 */

// Literal synthetic set, in this order. Entry 4 (all-zero) is included unless the library rejects it.
const BASE_VALUES: LeafValue[] = [
  ["0x0000000000000000000000000000000000000001", "1000000000000000000000", "0"],
  [
    "0x0000000000000000000000000000000000000002",
    "50000000000000000000000",
    "50000000000000000000000",
  ],
  [
    "0x0000000000000000000000000000000000000003",
    "25000000000000000000000",
    "10000000000000000000000",
  ],
  ["0x0000000000000000000000000000000000000004", "0", "0"],
];

interface FixtureEntry {
  account: string;
  snapshotBmx: string;
  snapshotPoints: string;
  proof: string[];
}

function tryBuild(values: LeafValue[]): StandardMerkleTree<LeafValue> {
  return StandardMerkleTree.of(values, [...LEAF_ENCODING]);
}

function main(): void {
  // Include the all-zero 4th entry if the library accepts it; otherwise fall back to the first 3.
  let values: LeafValue[] = BASE_VALUES;
  let tree: StandardMerkleTree<LeafValue>;
  try {
    tree = tryBuild(values);
  } catch (e) {
    console.warn(
      `[fixture] StandardMerkleTree rejected the all-zero entry; using first 3 entries. (${String(
        e,
      )})`,
    );
    values = BASE_VALUES.slice(0, 3);
    tree = tryBuild(values);
  }

  const entries: FixtureEntry[] = [];
  for (const [i, value] of tree.entries()) {
    const proof = tree.getProof(i);
    const ok = StandardMerkleTree.verify(tree.root, [...LEAF_ENCODING], value, proof);
    if (!ok) {
      throw new Error(`[fixture] verify FAILED for ${value[0]} — encoding mismatch.`);
    }
    entries.push({
      account: value[0]!,
      snapshotBmx: value[1]!,
      snapshotPoints: value[2]!,
      proof,
    });
  }
  // Also exercise the static verify path on the full set against the root.
  for (const e of entries) {
    const ok = StandardMerkleTree.verify(
      tree.root,
      [...LEAF_ENCODING],
      [e.account, e.snapshotBmx, e.snapshotPoints],
      e.proof,
    );
    if (!ok) throw new Error(`[fixture] re-verify FAILED for ${e.account}.`);
  }

  // Reorder entries to match the original input order (tree.entries() is leaf-sorted) for stable docs.
  const byAccount = new Map(entries.map((e) => [e.account.toLowerCase(), e]));
  const ordered = values
    .map((v) => byAccount.get(v[0].toLowerCase()))
    .filter((e): e is FixtureEntry => e !== undefined);

  writeJson(fixturePath("migration-fixture.json"), {
    root: tree.root,
    leafEncoding: LEAF_ENCODING,
    note: "Synthetic deterministic fixture for BwsMigration tests. snapshotBmx/snapshotPoints in wei.",
    entries: ordered,
  });

  writeText(fixturePath("solidity-fixture.txt"), soliditySnippet(tree.root, ordered));

  // stdout report.
  console.log(`root: ${tree.root}`);
  for (const e of ordered) {
    console.log(
      `\naccount:        ${e.account}` +
        `\nsnapshotBmx:    ${e.snapshotBmx}` +
        `\nsnapshotPoints: ${e.snapshotPoints}` +
        `\nproof:          ${JSON.stringify(e.proof)}`,
    );
  }
  console.log(
    `\n[fixture] wrote fixtures/migration-fixture.json and fixtures/solidity-fixture.txt`,
  );
  console.log(`[fixture] all ${ordered.length} entries verify against the root.`);
}

function soliditySnippet(root: string, entries: FixtureEntry[]): string {
  const lines: string[] = [];
  lines.push("// Deterministic BwsMigration merkle fixture (generated by buildFixture.ts).");
  lines.push("// Leaf encoding: ['address','uint256','uint256'] (StandardMerkleTree).");
  lines.push("");
  lines.push(`bytes32 constant MERKLE_ROOT = ${root};`);
  lines.push("");
  entries.forEach((e, i) => {
    const n = i + 1;
    lines.push(`// entry ${n}`);
    lines.push(`address constant ACCOUNT_${n} = ${e.account};`);
    lines.push(`uint256 constant SNAPSHOT_BMX_${n} = ${e.snapshotBmx};`);
    lines.push(`uint256 constant SNAPSHOT_POINTS_${n} = ${e.snapshotPoints};`);
    if (e.proof.length === 0) {
      lines.push(`bytes32[] PROOF_${n}; // empty proof (single-leaf or matched sibling)`);
    } else {
      lines.push(`function proof${n}() internal pure returns (bytes32[] memory p) {`);
      lines.push(`    p = new bytes32[](${e.proof.length});`);
      e.proof.forEach((h, j) => {
        lines.push(`    p[${j}] = ${h};`);
      });
      lines.push(`}`);
    }
    lines.push("");
  });
  return lines.join("\n") + "\n";
}

main();
